// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectFooBar() FooBar {
	fooFunc := func() func() Foo {
		var instance Foo
		var wasSet bool
		return func() Foo {
			if !wasSet {
				wasSet = true
				instance = provideFoo()
			}
			return instance
		}
	}()
	barFunc := func() func() Bar {
		var instance Bar
		var wasSet bool
		return func() Bar {
			if !wasSet {
				wasSet = true
				instance = provideBar(fooFunc)
			}
			return instance
		}
	}()
	fooBar := provideFooBar(barFunc)
	return fooBar
}
