// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/craiggwilson/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectFooBar() (FooBar, error) {
	foo := provideFoo()
	barFunc := func() func() (Bar, error) {
		var instance Bar
		var wasSet bool
		var err error
		return func() (Bar, error) {
			if !wasSet {
				wasSet = true
				instance, err = provideBar()
			}
			return instance, err
		}
	}()
	fooBar, err := provideFooBar(foo, barFunc)
	if err != nil {
		return 0, err
	}
	return fooBar, nil
}
