// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/craiggwilson/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectFooBar() FooBar {
	foo := provideFoo()
	barFunc := func() func() Bar {
		var instance Bar
		var wasSet bool
		return func() Bar {
			if !wasSet {
				wasSet = true
				instance = provideBar()
			}
			return instance
		}
	}()
	fooBar := provideFooBar(foo, barFunc)
	return fooBar
}
